swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transationCurrentMonth:
    get:
      tags:
        - User Module
      summary: Transation
      description: API for visualize current month transation
      responses:
        '200':
          description: successfully operation
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/{transationId}:
    get:
      tags:
        - User Module
      summary: Find transation by ID
      description: Returns a single pet
      operationId: getTransationById
      parameters:
        - name: transationId
          type: integer
          format: int64
          in: path
          description: ID of transation to return
          required: true
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Transation not found
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete an existing transation
      description: Delete an existing transation
      parameters:
        - name: Authorization
          type: string
          in: header
          description: Attach Bearer JWT token
          required: true
        - name: transationId
          type: integer
          format: int64
          in: path
          description: delete Id transition
          required: true
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Transation not found
        '500':
          description: Internal Server Error
  /user/transation:
    post:
      tags:
        - User Module
      summary: Add new transation
      description: Add new transation
      parameters:
        - in: body
          name: body
          description: value form
          required: true
          schema:
            $ref: '#/definitions/TransationId'
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/TransationId'
        '405':
          description: Invalid input
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update an existing transation
      description: Update an existing transation
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update transation attributes
          required: true
          schema:
            $ref: '#/definitions/TransationId'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransationId:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 20
      date:
        type: string
        example: 25/02/2022
      description:
        type: string
        example: note d'hôtel
      amout:
        type: integer
        format: int64
        example: 98
      balance:
        type: integer
        format: int64
        example: 2082.79
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      transation1:
        type: string
      transation2:
        type: string
      transation3:
        type: string
      transation4:
        type: string
